
#  Probability

## PETE 2061 Lab 5 Workbook 

## THIS IS DUE BY 11:59 PM ON SUNDAY (Sept 29, 2019)

1. Paste the url (or link) to the pete2061 folder in your github account in the "marked down" cell below. <br>

2. **Using the example in "lab5_Probability.ipynb", write a Python code to compute the probabililities of all possible total values that can be obtained from rolling a fair die three times**

In [2]:
import itertools
import pandas as pd
import numpy as np
x = list(range(1,7))
y = list(itertools.product(x,repeat=int(input("Number of Dice = "))))
z = np.array(y)

print(f"Total number of outcomes = {len(y)}")
sumOutcomes = np.sum(z, axis=1)
d = pd.DataFrame({"outcomes":y,"sumOutcomes":sumOutcomes})
d

by_sumOutcomes = d.groupby("sumOutcomes")
by_sumOutcomes.describe()
outcomeDF = by_sumOutcomes.count()
outcomes = outcomeDF.values[:,0]
probability = (outcomes / np.sum(outcomes))*100
f = pd.DataFrame({"Sum of Three Dice":d["sumOutcomes"].unique(), "Outcomes":outcomes, "% Probability":probability})
f

Number of Dice = 5
Total number of outcomes = 7776

    Sum of Three Dice  Outcomes  % Probability
0                   5         1       0.012860
1                   6         5       0.064300
2                   7        15       0.192901
3                   8        35       0.450103
4                   9        70       0.900206
5                  10       126       1.620370
6                  11       205       2.636317
7                  12       305       3.922325
8                  13       420       5.401235
9                  14       540       6.944444
10                 15       651       8.371914
11                 16       735       9.452160
12                 17       780      10.030864
13                 18       780      10.030864
14                 19       735       9.452160
15                 20       651       8.371914
16                 21       540       6.944444
17                 22       420       5.401235
18                 23       305       3.922325
19                 24       205       2.636317
20                 25       126       1.620370
21                 26        70       0.900206
22                 27        35       0.450103
23                 28        15       0.192901
24                 29         5       0.064300
25                 30         1       0.012860